//
//  MainInteractor.swift
//  CleanSwiftTest
//
//  Created by Dave on 5/19/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

protocol MainBusinessLogic
{
    func fetchData()
    func rowSelected(item: Places)
}
 

class MainInteractor: MainBusinessLogic
{
     
    var presenter: MainPresentationLogic?
    var worker: CoreDataManagerProtocol?
    
    // MARK: Do something
      
    func rowSelected(item: Places) {
        
    }
    
    func fetchData() {
        guard let data = worker?.fetchData() else {return}
        let items = MainModel.Items.Response(data: data)
        presenter?.presentData(items: items)
    }
}
