//
//  MainRouter.swift
//  CleanSwiftTest
//
//  Created by Dave on 5/19/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic
{
    var navigationController: UINavigationController? { get }
    
    func routeToDetails(with index: Int)
}


class MainRouter: NSObject, MainRoutingLogic
{
    
    weak var navigationController: UINavigationController?
    
    
    weak var viewController: MainViewController?
    
    
    // MARK: Navigation
    func routeToDetails(with index: Int) {
        let detailVC = DetailsViewController()
        let router = DetailsRouter()
        router.viewController = detailVC
        detailVC.setup(index: index)
        
        navigationController = viewController?.navigationController
        navigationController?.pushViewController(detailVC, animated: true)
    } 
}
