//
//  MainPresenter.swift
//  CleanSwiftTest
//
//  Created by Dave on 5/19/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentData(items: MainModel.Items.Response)
}

class MainPresenter: MainPresentationLogic {
    
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentData(items: MainModel.Items.Response) {
        var titles : [String] = []
        for item in items.data {
            guard let title = item.titile else {
                return
            }
            titles.append(title)
        }
        let item = MainModel.Items.ViewModel(title:titles)
        viewController?.displayData(items: item)
    }
}
