//
//  DetailsWorker.swift
//  CleanSwiftTest
//
//  Created by Dave on 5/19/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailsWorker
{
    enum DataResult {
       case success(Data)
       case failure(Error)
    }
    
    func downloadImage(from url: URL, completion: @escaping (DataResult) -> ())
    {
        URLSession.shared.dataTask(with: url) { data, response, error in
            guard
                let httpURLResponse = response as? HTTPURLResponse, httpURLResponse.statusCode == 200,
                let data = data, error == nil
            else { return }
            completion(.success(data))
        }.resume() 
    }
}
