//
//  DetailsRouter.swift
//  CleanSwiftTest
//
//  Created by Dave on 5/19/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailsRoutingLogic
{
    var navigationController: UINavigationController? { get }
    func routeBackToMain()
}
 

class DetailsRouter: NSObject, DetailsRoutingLogic
{
    var navigationController: UINavigationController?
    
    weak var viewController: DetailsViewController?
    
    func routeBackToMain() {
        navigationController = viewController?.navigationController
        navigationController?.popViewController(animated: true)
    }
}
