//
//  DetailsModels.swift
//  CleanSwiftTest
//
//  Created by Dave on 5/19/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DetailsModel
{
  // MARK: Use cases
  
  enum Item
  {
    struct Request
    {
    }
    struct Response
    {
        var title: String
        var details: String
        var image: Data
    }
    struct ViewModel
    {
        var title: String
        var details: String
        var image: Data
    }
  }
}
