//
//  DetailsPresenter.swift
//  CleanSwiftTest
//
//  Created by Dave on 5/19/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic
{
    func sendData(item: DetailsModel.Item.Response)
    func itemDeleted()
}

class DetailsPresenter: DetailsPresentationLogic
{
    
    weak var viewController: DetailsDisplayLogic?
    
    // MARK: Do something
    
    func sendData(item: DetailsModel.Item.Response) {
        let item = DetailsModel.Item.ViewModel.init(title: item.title, details: item.details, image: item.image)
        viewController?.displayData(item: item)
    }
    
    func itemDeleted() {
        viewController?.routeToMain()
    }
}
